const generalUNCQuestions = [
    'Used the escalators as a shortcut in the Student Stores',
    'Snuck food out of the dining halls',
    'Snuck a plate/silverware out of the dining halls',
    'Argued with the pit preacher',
    'Used Google Maps to find your classes',
    'Mispronounced Dey Hall',
    'Started as Pre-Med',
    'Switched out of Pre-Med',
    'Did the 2 AM Davis to UL walk of shame',
    'Ate Wendys for lunch and dinner',
    'Have more than 5 UNC shirts',
    'Have more than 10 UNC shirts',
    'Stole a brick outside Rams',
    'Went streaking on LDOC',
    'Had someone from NC State call you a rival',
    'Used "Tar Heel Born, Tar Heel Bred.." in an Instagram Caption',
    'Pulled an all nighter at the UL',
    'Got a picture with a basketball player',
    'Never won the Basketball Lottery',
    'Call it Chase not Rams',
    'Slept with an athlete'
];