const generalUNCQuestions = [
    'Used the escalators as a shortcut in the Student Stores',
    'Snuck food out of the dining halls',
    'Snuck a plate/silverware out of the dining halls',
    'Argued with the pit preacher',
    'Used Google Maps to find your classes',
    'Mispronounced Dey Hall',
    'Started as Pre-Med',
    'Used a fake ID on Franklin',
    'Switched out of Pre-Med',
    'Did the 2 AM Davis to UL walk of shame',
    'Ate Wendys for lunch and dinner',
    'Have more than 5 UNC shirts',
    'Have more than 10 UNC shirts',
    'Stole a brick outside Rams',
    'Went streaking on LDOC',
    'Lived through a water crisis',
    'Had someone from NC State call you a rival',
    'Used "Tar Heel Born, Tar Heel Bred..." in an Instagram Caption',
    'Pulled an all nighter at the UL',
    'Got a picture with a basketball player',
    'Never won the Basketball Lottery',
    'Call it Chase not Rams',
    'Slept with an athlete',
    'Posted a meme on the Facebook group',
    'Committed a housing violation',
    'Joined a frat or sorority',
    'Roasted someone on Piazza',
    'Snuck into a building after hours',
    'Fell on the P2P',
    'Lived in HoJo'
];