const generalUNCQuestions = ['Used the escalators as a shortcut in the Student Stores',
    'Snuck food out of the dining halls',
    'Snuck a plate/silverware out of the dining halls',
    'Argued with the pit preacher',
    'Used Google Maps to find your classes',
    'Mispronounced Dey Hall',
    'Started as Pre-Med',
    'Switched out of Pre-Med',
    'Walked through a protest to get to class',
    'Used a fake ID on Franklin',
    'Did the 2 AM Davis to UL walk of shame',
    'Ate Wendys for lunch and dinner',
    'Have more than 5 UNC shirts',
    'Have more than 10 UNC shirts',
    'Found a textbook PDF online',
    'Stole a brick outside Rams',
    'Went streaking on the midnight before finals',
    'Lived through a water crisis',
    'Had someone from NC State call you a rival',
    'Used "Tar Heel Born, Tar Heel Bred..." in an Instagram Caption',
    'Pulled an all nighter at the UL',
    'Woke up ten minutes before class and still made it on time',
    'Got a picture with a basketball player',
    'Never won the basketball lottery',
    'Call it Rams and not Chase',
    'Randomly assigned group project with an athlete',
    'Posted a meme on the Facebook group',
    'Committed a housing violation',
    'Missed the Sakai deadline because it was due at "11:55 PM"',
    'Submitted something on Sakai a minute before the deadline',
    'Rushed a frat or sorority',
    'Roasted someone on Piazza',
    'Snuck into a building after hours',
    'Closed out at MAW at 2 AM',
    'Danced on the table at MAW',
    'Fell on the P2P',
    'Lived in HoJo',
    'Had mold grow in your dorm room',
    'Got into a class using Coursicle',
    'Lost your keys on campus',
    'Lost your OneCard',
    'Had Wi-Fi troubles on campus',
    'Consistently skipped a class',
    'Went to a concert at Cats Cradle',
    'Sat in the last row of a classroom on purpose',
    'Got blacklisted on Handshake',
    'Done the Linda\'s birthday shot',
    'Gotten drunk with one of your professors',
    'Hooked up with a professor',
    'Set off a fire alarm in a dorm',
    'Snuck into a dining hall without swiping in',
    'Got kicked out of a study room',
    '"Does anyone have an extra scantron/bluebook?"',
    'Used someone else\'s swipes',
    'Threw up on Franklin St',
    'Not contributed to a group project',
    'Done the whole group project',
    'Been in the DTH',
    'Saw protestors outside Silent Sam',
    'Roasted a professor on a class eval',
    'Snuck into a party with a fake wristband',
    'Asked people to take your survey for class',
    'Actually enjoy I ♥ N.Y. Pizza',
    'Joined an intramural team',
    'Got lost in Phillips',
    'Went to class under the influence',
    'Gotten passed by a bus/P2P',
    'Almost got hit by a bus/P2P',
    'Went to an event only for free stuff',
    'Went to Waffle House before midnight',
    'Went to a Little Frat Court Concert',
    'Drank from the Old Well on FDOC',
    'Bought basketball tickets',
    'Sold basketball tickets',
    'Got a parking ticket on campus',
    'Didn\'t get a ticket when you probably should have',
    'Got sent to honor court',
    'Said "GDTBATH" sarcastically when it wasn\'t',
    'Found a secret study spot',
    'Got screwed over by registration',
    'Begged a professor to let you into a class',
    'Asking your friends if they have old tests for a class',
    'Got a CCI laptop but never use it',
    'Cried in the bathroom at the library',
    'Smoked in the woods on south campus',
    'Hid "contraband" during a room inspection',
    'Convinced your friends to go on a Cookout run',
    'Matched with a classmate on Tinder (or whatever dating app you use)',
    'Matched with a TA on Tinder',
    'Considered buying a Chegg account',
    'Bought a Chegg account',
    'Left a class to get food',
    'Rushed Franklin when you weren\'t supposed to',
    'Stole something from a frat house',
    'Only got into one class during registration',
    'Stayed in the dining hall between meals to save a swipe',
    'Went to campus health and they didn\'t know what was wrong with you',
    'Got norovirus, strep throat, or mono',
    'Done a pickleback shot at Goodfellows',
    'Went to 5$ blue cups and pint night in the same week'
];

const toBeAnnounced = ['Do you have an idea for another category?',
    'Or another feature that would be cool?',
    'Let me know on the next screen and I\'ll try and add it!',
    'It really could be anything honestly'
];